version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ant
      MONGO_INITDB_ROOT_PASSWORD: 1qaz!QAZ
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ant
      POSTGRES_PASSWORD: 1qaz!QAZ
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # redis:
  #   image: redis:7.2
  #   container_name: redis-acl
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #     - ./redis.conf:/usr/local/etc/redis/redis.conf
  #     - ./users.acl:/usr/local/etc/redis/users.acl
  #   command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  #   restart: unless-stopped

volumes:
  pgdata:
  mongo_data:
  # redis_data:
